data/UpgradeData_Upcoming.xml, entity/OmsServiceEntities.xml
Closes #3 
1. Extended ServiceJob entity to include parentJobName field so that it can be referenced in the cloned Service Job
=> Improved: Extended ServiceJob entity to include parentJobName field (#3)

entity/OmsOrderViewEntities.xml
Closes #13 
This is done for below scenario
1. The same order has a return and an appeasement.
2. The view should include ReturnItemResponse entity with join-optional true as for Sales, this entity does not hold records, but it contains records for Returns and Appeasements.
3. Now for Sales Items, we can fetch payment details using order Id and statusId = 'PAYMENT_SETTLED'.
4. For Return Items, we can fetch payment details using return Id and statusId = 'PAYMENT_REFUNDED'.
5. For Appeasements, we can fetch payment details using return Id and statusId = 'PAYMENT_REFUNDED'.
6. This way we can correctly fetch details for the return and appeasement for the same order.
=> Improved: Included ReturnItemReponse in OrderPaymentPreferenceAndType View

entity/OmsOrderViewEntities.xml
1. Included ReturnItemReponse in OrderPaymentPreferenceAndType.
2. This is done for below scenario
- The same order has a return and an appeasement.
- The view should include ReturnItemResponse entity with join-optional true as for Sales, this entity does not hold records, but it contains records for Returns and Appeasements.
- Now for Sales Items, we can fetch payment details using order Id and statusId = 'PAYMENT_SETTLED'.
- For Return Items, we can fetch payment details using return Id and statusId = 'PAYMENT_REFUNDED'.
- For Appeasements, we can fetch payment details using return Id and statusId = 'PAYMENT_REFUNDED'.
- This way we can correctly fetch details for the return and appeasement for the same order.
=> Improved the view of Order Payment Preference

entity/OmsOrderViewEntities.xml
closes #7 
1. Added join-optional as true for OrderItemShipGrpInvRes entity in BrokeredOrderItemsSyncQueue view for scenarios where HC is not doing reservations.
=> Improved: Updated BrokeredOrderItemsSyncQueue view to have inventory reservations as optional for scenarios where HC is not doing reservations (#7)

entity/OmsProductViewEntities.xml
closes #16 
1. Added view ProductStoreCatalogAndCategoryMembers to identify the product categories for a product.
2. Included the following entities in the view:
1. ProductStoreCatalog
2. ProdCatalogCategory
3. ProductCategoryMember 
3. The view has the following fields:
1. productCategoryId
2. prodCatalogCategoryTypeId
3. productId
4. productCategoryMemberFromDate
5. productCategoryMemberThruDate
6. productStoreId
=> Added: View for Product Catalog and Category Members (#16)

entity/OmsProductViewEntities.xml
1. Merge changes of the new view added for Product Catalog Category Members into main branch
2. The view is required for the fix in Shopify Inventory Feed to include isPreOrder and isBackOrder fields to identify if product is in Pre Order and/or Back Order Category.
3. Created this PR to merge changes into main, and then we will cut the tag from main for the fix.
=> Merge view product catalog category members into main

entity/OmsOrderViewEntities.xml
Closes #1 
1. Added the ShipmentOrderItemsSyncQueue View for shipment order Items.
2. New view to fetch Fulfilled Order Items, for this we should include data model for Shipment Item and related entities.
3. The view could contain items which are packed etc, based on the Shipment Status, the view will be used to prepare the Fulfilled Order Items Feed, as the status will be 'SHIPMENT_SHIPPED' for such records.
=> Added: View for shipment order Items (#1)

entity/OmsOrderViewEntities.xml
closes #22
1. Used the OrderFulfillmentHistory entity to keep logs for the Fulfilled Order and Items Feed.
2. If orderItem exists for the same orderId and OrderItemSeqId then update the order instead of creating new records.
=> Improved: OrderFulfillmentHistory entity in OrderItemAndShipmentSyncQueue view (#22)

entity/HwmappsEntitymodel.xml, entity/OmsOrderViewEntities.xml
closes #35 
The OrderAdjustmentHistory entity already exists, and is being used for maintaining the history of the adjustments sent as part of the Brokered Order Items Feed, so added a separate entity for the adjustments sent as part of fulfilled items.
Added the FulfilledOrderAdjustmentAndHistory view for fetching the eligible order level adjustment.
=> Added: New entity for Order Adjustment History for fulfilled Order Items (#35)

entity/OmsOrderViewEntities.xml
closes #38 
Added the reservedDatetime field in Brokered Order Item Sync Queue view for fetching the reserved Date time for brokered order items feed.
=> Added: Reserved Date time field in BrokeredOrderItemsSyncQueue view (#38)

entity/OmsShipmentViewEntities.xml
closes - #44 
As discussed we will use the existing view `ShipmentAndItemAndReceipt` to fetch the eligible orders.
We only need to add the serialNumber field in the existing view.
=> Improved: ShipmentAndItemAndReceipt view to add the serialNumber (#44)

entity/HwmappsEntitymodel.xml, entity/OmsShipmentViewEntities.xml
closes- #44
Discussed  we will use externalId to prepare the line_id for Transfer Order Shipments Feed instead of serialNumber.
Since the serialNumber field is used for serialized inventory shipment.
1. **NOTE:**  We need to add the field external Id in the ShipmentItem entity, since in the ofbiz entity data model we have extended the field externalId in the ShipmentItem entity.
2. Added the externalId as shipmentItemExternalId in the ShipmentAndItemAndReceipt view.
=> Improved: Included externalId in ShipmentAndItemAndReceipt view entity

entity/DatamodelOrderEntitymodel.xml, entity/OmsFinancialViewEntities.xml
close https://github.com/hotwax/ofbiz-mantle-udm/issues/55
1. Added the Support of return Channel Enum Id in Returns Financial Feed to fetch all returns completed from any specific Channels and it can be warehouse or happy returns, In-Store etc.
2. Added the return Channel Enum Id in FinancialReturnItemsSyncQueue view.
3. Added the return Channel Enum Id in the ReturnHeader entity.
=> Support of return Channel Enum Id in FinancialReturnItemsSyncQueue view

entity/DatamodelOrderEntitymodel.xml, entity/OmsFinancialViewEntities.xml
Support of return Channel Enum Id in Returns Financial Feed to fetch all returns completed from any specific Channels and It can be Ecom Return or In-Store etc.
=> Cherry pick Support of return Channel Enum Id in FinancialReturnItemsSyncQueue view 

entity/OmsOrderViewEntities.xml
1. Included Order item level itemDescription field to BrokeredOrderItemSyncQueue View.
2. This field is required by external system for Brokered Order details.
=> Improved: Included Order Item itemDescription field to BrokeredOrderItemsSyncQueue View

entity/OmsShipmentViewEntities.xml
Closes - https://github.com/hotwax/ofbiz-mantle-udm/issues/70
1. Earlier, In the ShipmentAndItemAndReceipt view entity, we have added the null check on the receipt ID of the ShipmentItemHistory which means get all the shipment items where the receipt ID does not exist in the shipmentItemHistory.
2. As per the issue - [1](https://git.hotwax.co/HC2/plugins/ofbiz-oms-mantle/-/issues/494) In the ShipmentAndItemAndReceipt view, we will add the check on the shipment ID of ShipmentItemHistory instead of the receipt ID.
=> Used shipmentId of shipmentItemHistory to filter records for ShipmentAndItemAndReceipt view entity

entity/OmsShipmentViewEntities.xml
1. The ShipmentItemHistory should be joined with ShipmentItem instead of ShipmentReceipt as now we create history for all items irrespective of the receipt.
2. The assumption is that a shipment item can be received only once, so we should create history for all items in the shipment.
=> ShipmentItemHistory joined with ShipmentItem instead of ShipmentReceipt in the ShipmentAndItemAndReceipt (#75)

entity/OmsOrderViewEntities.xml
- Added the quantity field of the OrderItem entity in the `BrokeredOrderItemsSyncQueue`.
- To distinguish the quantity fields of `OrderItem` and `OrderItemShipGrpInvRes` entities, we have changed the names as **orderItemQuantity** and **reservedItemQuantity** respectively.
- We just have to fetch quantity field's value from `OrderItem` as it is, hence didn't added any aggregate function.
Closes #82
=> Added: Added the quantity field of the OrderItem entity in the BrokeredOrderItemsSyncQueue(#82)

entity/OmsOrderViewEntities.xml
Added the quantity field of the OrderItem entity in the BrokeredOrderItemsSyncQueue, to distinguish the quantity fields of OrderItem and OrderItemShipGrpInvRes entities, we have changed the names as orderItemQuantity and reservedItemQuantity respectively, we just have to fetch quantity field's value from OrderItem as it is, hence didn't added any aggregate function. (#83)
=> Cherry Pick change for Added the quantity field in the Brokered Items view

entity/OmsOrderViewEntities.xml
Closes #85
1. Removed the shipGroupSeqId in OrderItemAssocAndShipment view.
=> Improved: Removed the shipGroupSeqId from OrderItemAssocAndShipment View (#85)

entity/OmsOrderViewEntities.xml
closes #99
Added the following fields in the Brokered Order Items Sync Queue
1. requestedDeliveryDate
2. requestedDeliveryTime
3. deliveryWindow
=> Added: Delivery related date and time in Brokered Order Items Sync Queue view

entity/OmsOrderViewEntities.xml
Closes #59 
1. Added Internal name field from Product entity in BrokeredOrderItemSyncQueue view.
2. Product entity already existed in the view, so only a filed is added.
=> Improved: Added Product Internal Name field in BrokeredOrderItemSyncQueue view

entity/OmsShopifyViewEntities.xml
Joined product type entity in Shopify Product Inventory view.
This change is required to get the Product type id and isPhysical check in Shopify Inventory feed service.
=> Improved: Included product type entity in Shopify Product Inventory View (#27)

entity/OmsOrderViewEntities.xml
1. Removing the check of orderTypeId of SALES_ORDER.
2. Adding default value for orderTypeId parameter as SALES_ORDER in service so that if no value passed, it will by default create feed for fulfilled sales orders.
=> Improved: Removed the orderTypeId check from FulfilledOrderItemsSyncQueue(#916)

entity/OmsOrderViewEntities.xml
1. Updated Order Item and Shipment Partial Fulfillment view entity to include order level details like shopId and orderTypeId.
2. Now this view can be used in place of Fulfilled Order Sync View to fetch Fulfilled Orders details in Fulfilled Order Items Feed.
=> Improved: Order Item and Shipment Partial Fulfillment view

entity/OmsShopifyViewEntities.xml
1. This view entity is necessary for the Shopify Inventory feed, where we require Configuration facility IDs for specific Facility Groups.
Here is the parent issue for the reference:- [issue-1036](https://git.hotwax.co/HC2/plugins/ofbiz-oms-usl/-/issues/1036) , [#note_197161](https://git.hotwax.co/HC2/plugins/ofbiz-oms-usl/-/merge_requests/435#note_197161)
Closes https://github.com/hotwax/ofbiz-oms-udm/issues/139
=> View entity to fetch Facility and Facility Group Member details

entity/OmsOrderViewEntities.xml
1. Improved: replaced facility not equals _NA_ check with parent type id not equals Virtual Facility in Brokered Order Items Sync Queue view to exclude orders from ineligible facilities in Brokered Orders feed.
=> Improved: excluded virtual facility orders in Brokered Orders Items Sync View

entity/OmsOrderViewEntities.xml
Improved: replaced facility not equals _NA_ check with parent type id not equals Virtual Facility in Brokered Order Items Sync Queue view to exclude orders from ineligible facilities in Brokered Orders feed
=> Cherry Pick change of BrokeredOrderItemsSyncQueue for virtual facility type check

entity/OmsOrderViewEntities.xml
1. This is done to handle the case when destinationFacilityId is null for a return.
=> Improved: Added join optional for Facility entity in ReturnItemView 

entity/OmsOrderViewEntities.xml
In this PR,  
Added Uom, ShopifyShopOrder, Enumeration, Product, ProductType entities in the SalesOrderView and fields that needed to generate the fulfilled order items feed for Shopify/ERP.
=> Added the required fields in the SalesOrderView needed in the FulfilledOrderItemsFeed

entity/OmsOrderViewEntities.xml
In this PR, 
Added FulfilledOrdersItemsForShopify and OrderItemShipmentForShopify view. this view is required to fetch the eligible orders for the fulfilled items feed for Shopify.
=> Added views for Fulfilled Order Items for Shopify

entity/OmsOrderViewEntities.xml
1. We need to include the order facility id in the Fulfilled Order Items feed so included this field in the Order Item and Shipment view.
=> Improved: included order facility id in Order Item and Shipment view

entity/HwmappsEntitymodel.xml
Added createdDate and createdByUserLoginId columns in InventoryCountImportItem table. As some NiFi flows are dependant on the "Created Stamp" (auto generated field of OFBiz) field and from new Cycle count app (based on Moqui) it is not set.
=> Improved: Added createDate and createdByUserLoginId column in InventoryCountImportItem table (#215).

entity/OmsOrderViewEntities.xml
Cloning the `VirtualFacilityOrderItemCount` view-entity from the OMS to get the order products count currently present in the virtual queues.
=> Added the view-entity to get the virtual queue items count

entity/HwmappsEntitymodel.xml
Done following - 
1) Added importItemSeqId field in InvCountImportStatus entity in order to start tracking item level status change.
2) Corrected createdByUserLoginId and countedByUserLoginId field type to match the UserLogin.userLoginId field.
=> Improved: Added importItemSeqId field in InvCountImportStatus entity in order to start tracking item level status change

entity/OmsInventoryViewEntities.xml
- Currently, when syncing inventory adjustments to NetSuite, we send Inventory cycle by HotWax  in the memo field. Instead, we need to send the count name in this field.
=> Added the field 'countImportName' to the view entity 'InventoryCountImportVariance'

entity/OmsOrderViewEntities.xml
1. Added orderSalesChannel, orderSalesChannelenumId and shopId in the ReturnItemView as they have been removed from the header level so adding them at Item level
=> Added: orderSalesChannel, orderSalesChannelenumId and shopId in the ReturnItemView

entity/DatamodelOrderEntitymodel.xml, entity/OmsOrderViewEntities.xml
https://github.com/hotwax/ofbiz-oms-udm/issues/269
From now on, the **`OrderItemShipGroupAssoc` database table is no longer the source of truth** for the order item and ship group relationship. It may contain **stale or missing data**.
**Update all custom SQL queries** and code references with the following mappings:
|Old Reference|New Mapping|
| --- | --- |
|`OrderItemShipGroupAssoc.orderId`|`OrderItem.orderId`|
|`OrderItemShipGroupAssoc.orderitemSeqId`|`OrderItem.itemSeqId`|
|`OrderItemShipGroupAssoc.quantity`|`OrderItem.quantity`|
|`OrderItemShipGroupAssoc.cancelQuantity`|`OrderItem.cancelQuantity`|
|`OrderItemShipGroupAssoc.shipGroupSeqId`|`OrderItem.shipGroupSeqId`|
> When joining with `OrderItemShipGroup`, use:
sql
```
ON OrderItem.orderId = OrderItemShipGroup.orderId
AND …
```
=> Order item ship group assoc removal

data/BSeedExtCommerceTypeData.xml, data/StorefulfillmentSeedData.xml
Related Issue: https://github.com/hotwax/oms/issues/173
Introducing a `REJ_CASCADE_BY_PROD` (new rejection reason enum ID), for the cases where items are rejected due to collateral rejection or cascading by product.
=> Define a new rejection reason enumeration of type no variance
