hotwax/ofbiz-oms-udm

entity/OmsShopifyViewEntities.xml
closes #8 
1. Added relation with ProductStoreFacility and use the productStoreId from the ProductStoreFacility entity.
2. Updated the relation of ProductStore from ShopifyShop to ProductStoreFacility.
3. Added the lastUpdatedStamp of FacilityGroupMember.
4. Removed the date filter on fromDate and thruDate of FacilityGroupMember
=> Improved: View to fetch Shopify Product Inventory (#8)

data/UpgradeData_v1.0.0.xml
closes #10 
1. Renamed the upgrade file from UpgradeData_Upcoming.xml to UpgradeData_v1.0.0.xml.
2. Updated the data reader of the file from ext-upgrade-dev to ext-upgrade.
=> Updated: Data reader in upgrade data file (#10)

entity/OmsFinancialViewEntities.xml
Closes #20 
1. Added the member entity ProductStore with a join from OrderHeader to include the externalId from ProductStore.
2. Added field orderName from OrderHeader.
3. Added field fromPartyId from ReturnHeader.
=> Improved: FinancialReturnItemsSyncQueue view entity (#20)

entity/OmsOrderViewEntities.xml
1. Used the ShipmentPackageRouteSeg entity for tracking code.
=> Improved: Used Shipment Package and related entities in OrderItemAndShipmentSyncQueue view (#24)

entity/OmsFinancialViewEntities.xml
Closes #31 
1. Added the returnDate field from the ReturnHeader entity.
=> Improved: FinancialReturnItemsSyncQueue to include returnDate (#31)

entity/OmsOrderViewEntities.xml
Added the reservedDatetime field in Brokered Order Item Sync Queue view for fetching the reserved Date time for brokered order items feed.
=> Merge change of reserveddatetime field in Brokered Items View into main

entity/OmsOrderViewEntities.xml
Closes #34 
1. Created the OrderItemAndShipmentSyncQueueNew for fetching the Order Item Level information.
2. Created the ShipmentItemView for fetching the Shipment Item Level information.
=> Improved: Added separate views for fetching Fulfilled Order Item and Shipment Details instead of single view (#34)

entity/OmsShipmentViewEntities.xml
1. Added the view entity to get the details of Purchase Order Items and Shipments
Closes #42
=> Added: View entity for Purchase Order and Shipments (#42)

entity/OmsOrderViewEntities.xml
closes #51 
Included the Facility Type entity as a member entity in  ReturnItemView for fetching the facilityTypeId,parentTypeId field
=> Added: Included Facility Type entity in the ReturnItemView (#51)

entity/OmsInventoryViewEntities.xml
Added the view entity to get the details of Purchase Order Items and Shipments
Closes https://github.com/hotwax/ofbiz-mantle-udm/issues/46
=> Added view for Inventory Count Import Variance

entity/OmsOrderViewEntities.xml
closes #68 
1. Included the Order Facility Id in BrokeredOrderItemsSyncQueue view
=> Added: Included Order Facility Id field in BrokeredOrderItemsSyncQueue view (#68)

entity/OmsOrderViewEntities.xml
Support of Order Facility Id in WH Brokered Order Items Feed to fetch the Order facility for send sale orders
=> Cherry Pick change for orderFacilityId and orderExternalId in Brokered Items View into main

component.xml
closes #87 
1. updated the version number in component.xml file for the upcoming release.
=> Updated: Version in the component.xml file for the upcoming release

entity/OmsOrderViewEntities.xml
1. Added the MaySplit field in OrderItemAndShipment view
=> Added: Included May Split field in OrderItemAssocAndShipment view (#685)

entity/OmsOrderViewEntities.xml
Closes #97
1. Added carrierPartyId from Order Item Ship Group in the Brokered Order Items Sync Queue.
=> Added: Carrier Party Id in the Brokered Order Items Sync Queue View

entity/OmsServiceEntities.xml
Extended SystemMessage entity to include Shop Id field so that it can be referenced in the generating Feeds.
=> Improved: Extended SystemMessage entity to include shop Id  field

entity/OmsOrderViewEntities.xml
1. Added the Shopify Config Id in FulfilledOrderItemsSyncQueue View
=> Included: Shopify shop Id in FulfilledOrderItemsSyncQueue View (#787)

entity/OmsFinancialViewEntities.xml
1. Included ShopId support to FinancialReturnItemSyncQueue View
=> Included ShopId support to FinancialReturnItemSyncQueue View

entity/OmsOrderViewEntities.xml
Related dev issue - https://git.hotwax.co/HC2/plugins/ofbiz-oms-usl/-/issues/879
=> Improved: Added the actualCarrierCode field in OrderItemAndShipment view

entity/OmsOrderViewEntities.xml
1. Updated Order Item and Shipment Partial Fulfillment view name to Transfer Order Item And Shipment.
=> Improved: Update the Order Item and Shipment Partial Fulfillment view name

entity/OmsShopifyViewEntities.xml
closes https://github.com/hotwax/ofbiz-oms-udm/issues/138
=> Removed the view coditions  for Facility Group Type and Facility Type in ShopifyProductInventory view entity (#1036)

entity/OmsShopifyViewEntities.xml
Improved: Added condition to filter out expired facility group members from FacilityGroupAndMember view entity.
=> Improved: Added condition to filter out expired facility group members from FacilityGroupAndMember view entity.

entity/OmsOrderViewEntities.xml
This feature is created from tag V1.3.6 to V1.3.7 for testing purposes of the below flows
1. Get Orders
2. Search Orders 
3. Import Returns
=> View changes for Hotwax To Predict Spring Integration

entity/OmsProductViewEntities.xml
Added ProductContentAndView entity
=> Added ProductContentAndView entity

entity/OmsOrderViewEntities.xml
=> Trac2 fild from Order Payment preference

entity/OmsOrderViewEntities.xml
=> Added the OrderAndItemsView

entity/OmsShopifyViewEntities.xml
Improved: Included parent facility type in FacilityGroupAndMember entity.
=> Improved: Included parent facility type in FacilityGroupAndMember entity.

entity/OmsOrderViewEntities.xml
1. Added the ReturnDate in ReturnItemView entity
=> Added: The Return Date in ReturnitemView

entity/OmsOrderViewEntities.xml
New Entities are added as part of the other PRs
=> Reverted the changes from the existing view entities OrderItemAndAjustments and ReturnItemAndAdjustments

entity/OmsOrderViewEntities.xml
1. Included UOM entity join and currency field in the AppeasementView view entity.
=> Improved: Added currency UOM in the AppeasementView

entity/OmsProductStoreViewEntities.xml
Implemented: Added view entities to get product store facility count and product store shipment method count. (#1075)
=> Implemented: Added view entities to get product store facility count and product store shipment method count. (#1075)

entity/OmsOrderViewEntities.xml
Added externa ID of return header in the Return Item View
=> Return External Id in Return Item View

entity/OmsOrderViewEntities.xml
=> Fixed: Return Adjustment and Item View to include facility ID from Return Header

entity/OmsOrderViewEntities.xml
=> Added OrderItemAndChange entity to fetch Order Item Change details

entity/OmsInventoryViewEntities.xml
Adding the facility name in the InventoryCountImportVariance view entity which is required for the InventoryCycleCountVarianceFeed
=> Improved: Adding the facilityId in the InventoryCountImportVariance view entity

entity/OmsInventoryViewEntities.xml
1. Used Enumeration instead of Variance Reason in ItemVarianceDetails to fetch variance reason description
=> Improved: used Enumeration instead of Variance Reason in ItemVarianceDetails to fetch variance reason description

entity/OmsOrderViewEntities.xml
Updated the OrderPaymentPreferenceAndType view by adding a field applicationIdentifier
=> Improved: OrderPaymentPreferenceAndType view by adding the applicationIdentifier field 

entity/OmsOrderViewEntities.xml
=> Removed: sum function on the quantity as items will not be grouped by Order Item's ExternalId

entity/OmsOrderViewEntities.xml
Reverts hotwax/ofbiz-oms-udm#195
=> Revert "Removed: sum function on the quantity as items will not be grouped by Order Item's ExternalId"

entity/HwmappsEntitymodel.xml
=> Modified the inventory cycle import entity model to support countName, dueDate and performed by party.

entity/OmsFinancialViewEntities.xml, entity/OmsOrderViewEntities.xml
1. Added returnTypeId in FinancialReturnItemsSyncQueue and ReturnItemView.
2. Added receivedQuantity in ReturnItemView.
=> Added: returnTypeId column and receivedQuantity field in Returns Financial feed related views

entity/OmsOrderViewEntities.xml
Added the geoName field from the Geo Entity to postalAddressView, as required by a brokered external system.
=> Added the geoName field in postalAddressView

entity/OmsInventoryViewEntities.xml
Added the FacilityAndProductFacility view entity available in OMS
Also I have added the totalLastInventoryCount field into this view
=> Added FacilityAndProductFacility view from OMS

README.md
This includes the version dependency information between `OMS` and `ofbiz-oms-udm`
=> Added the OMS compatible version for v1.4.4

entity/HwmappsEntitymodel.xml
Improved: Added countTypeEnumId column in InventoryCountImport entity to manage different types of count(#226).
=> Improved: Added countTypeEnumId column in InventoryCountImport entity to manage different types of count(#226)

entity/OmsOrderViewEntities.xml
Added promised datetime field from order item member in OrderItemDetail entity
=> Improvement: Added promised datetime field from order item member in OrderItemDetail entity

entity/OmsFacilityViewEntities.xml, entity/OmsProductViewEntities.xml
Added a new view entity as FacilityAndType
=> Improvement: Added a new view entity as FacilityAndType

entity/HwmappsEntitymodel.xml
Extended return id and return item sequence id in ItemIssuance entity and established relationships with return item
Changelog: Added
=> Extended return id and return item sequence id in ItemIssuance entity

entity/OmsShipmentViewEntities.xml
=> View to get ItemIssuance summary

entity/HwmappsEntitymodel.xml
=> Added fk-name in relationship with ReturnItem

entity/OmsShipmentViewEntities.xml
=> Added: ShipmentReceiptSummary view for total received quantity

entity/ServiceJobViewEntities.xml
- Updated the `ServiceJobAndProduct` view entity to allow jobs to show up in multiple job categories on the job-manager app.
=> Updated the ServiceJobAndProduct view entity

entity/OmsOrderViewEntities.xml
Closes: #297 Enhancement: Add the returnItemTypeId and the expectedItemStatus fields from the returnItem entity to the returnItemView
=> Enhancement: Add the returnItemTypeId and the expectedItemStatus fields from the returnItem entity to the returnItemView

entity/OmsOrderViewEntities.xml
This change is done corresponding to the PR https://github.com/hotwax/oms/pull/206/files for maySplit changes for TO.
=> Improved: OrderItemAndShipGroup to include OI.itemDescription

entity/DatamodelProductEntitymodel.xml
**Related Merge request**: https://git.hotwax.co/commerce/oms/-/merge_requests/6409
=> Enable audit log for closedDate field in Facility entity

entity/OmsEntities.xml
=> Added: ProductUpdateHistory entity in the OmsEntities.xml file
